config/routes.rb
Rails.application.routes.draw do
  resources :uploads
end

app/models/upload.rb
class Upload < ActiveRecord::Base
   mount_uploader :name, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  def create
    @upload = Upload.new(post_upload_params)
    puts '---------------------------------------------------------------'
    puts post_upload_params

    if @upload.save
      redirect_to @upload, notice: 'Upload was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /uploads/1
  def update
    if @upload.update(post_upload_params)
      redirect_to @upload, notice: 'Upload attachment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /uploads/1
  def destroy
    @upload.destroy
    redirect_to uploads_url, notice: 'Upload was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_upload_params
      params.require(:upload).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCarrierwaveS3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/uploads/index.html.erb
<% @uploads.each do |upload| %>
  <%= link_to upload do %>
  <img src="<%= upload.name.square %>">
  <% end %>
<% end %>

<br>

<%= link_to 'New upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New Upload</h1>

<%= form_for(@upload) do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.file_field :name %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<%= link_to 'Destroy', @upload,  method: :delete, data: { confirm: 'Are you sure?' } %>
<img src="<%= @upload.name.url %>" /><br/>
<img src="<%= @upload.name.large %>" /><br/>
<img src="<%= @upload.name.medium %>" /><br/>
<img src="<%= @upload.name.thumb %>" /><br/>
<img src="<%= @upload.name.square %>" /><br/>